import "./globals.css";
import Navbar from '../components/Navbar'
import { Rubik } from "next/font/google";

const rubik = Rubik({
  subsets:['latin'],
  weight:'400',
})


export const metadata = {
  title: "AniVerse",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${rubik.className}`}>
        <Navbar/>
        {children}
        </body>
    </html>
  );
}
